name: stopwatch
description: A simple stopwatch for a fitness app.
version: 1.3.0
author: Christophe Bonello
homepage: https://github.com/cbonello/
repository: https://github.com/cbonello/stopwatch
issue_tracker: https://github.com/cbonello/stopwatch/issues
publish_to: 'none'

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  desktop_window: ^0.4.0
  equatable: ^2.0.3
  flutter_bloc: ^7.0.0
  shared_preferences: ^2.0.0
  universal_platform: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true